import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Axe } from '@/components/Axe';
import { MSW } from '@/components/MSW';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Axe />
        <MSW />
        {children}
      </body>
    </html>
  );
}
